/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine;

import javax.swing.JOptionPane;

/**
 *
 * @author Erdem
 */
public class otomat extends javax.swing.JFrame {

    /**
     * Creates new form otomat
     */
    public otomat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bakiyeTf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        kolaRB = new javax.swing.JRadioButton();
        gazozRB = new javax.swing.JRadioButton();
        fantaRB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        alBt = new javax.swing.JButton();
        cikBt = new javax.swing.JButton();
        tekrarEkleBt = new javax.swing.JButton();
        temizleBt = new javax.swing.JButton();
        ekleCb = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Para Ekle : (TL) ");

        jLabel3.setText("Bakiye :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Vending Machine");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        bakiyeTf.setEditable(false);
        bakiyeTf.setText("0");
        bakiyeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyeTfActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ÜRÜN SEÇ"));

        kolaRB.setText("KOLA 15 TL");
        kolaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolaRBActionPerformed(evt);
            }
        });

        gazozRB.setText("GAZOZ 30 TL");
        gazozRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gazozRBActionPerformed(evt);
            }
        });

        fantaRB.setText("FANTA 20 TL");
        fantaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaRBActionPerformed(evt);
            }
        });

        jLabel4.setText("Her seferde sadece 1 (bir) ürün seçebilirsiniz.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kolaRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(fantaRB)
                        .addGap(139, 139, 139)
                        .addComponent(gazozRB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kolaRB)
                    .addComponent(gazozRB)
                    .addComponent(fantaRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        alBt.setText("Satın Al");
        alBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alBtActionPerformed(evt);
            }
        });

        cikBt.setText("Çıkış");
        cikBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikBtActionPerformed(evt);
            }
        });

        tekrarEkleBt.setText("Para Ekle");
        tekrarEkleBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekrarEkleBtActionPerformed(evt);
            }
        });

        temizleBt.setText("İşlemi İptal Et");
        temizleBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleBtActionPerformed(evt);
            }
        });

        ekleCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.5", "1", "5", "10" }));
        ekleCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cikBt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alBt))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(bakiyeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(temizleBt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(ekleCb, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tekrarEkleBt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tekrarEkleBt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(alBt)
                        .addComponent(jLabel2)
                        .addComponent(ekleCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cikBt)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(bakiyeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(temizleBt)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolaRBActionPerformed

        if (kolaRB.isSelected()) {
            fantaRB.setSelected(false);
            gazozRB.setSelected(false);   
        }
    }//GEN-LAST:event_kolaRBActionPerformed
        
    private void alBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alBtActionPerformed
       double para=0;
       para=Double.parseDouble((String) bakiyeTf.getText());
       //para=Double.parseDouble((String)ekleCb.getSelectedItem());
       
        if (kolaRB.isSelected()) {
            para = para - 15;
        }else if(fantaRB.isSelected()){
            para = para - 20;
        }else if(gazozRB.isSelected()){
            para = para - 30;
        }
       
       if (para < 0){
           JOptionPane.showConfirmDialog(rootPane, "Yeterli bakiye yok .. : "+para);
       }else{
           bakiyeTf.setText(Double.toString(para));
       }
    }//GEN-LAST:event_alBtActionPerformed

    private void cikBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikBtActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_cikBtActionPerformed

    private void temizleBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleBtActionPerformed

        
        kolaRB.setSelected(false);
        fantaRB.setSelected(false);
        gazozRB.setSelected(false);
        String bakiye=bakiyeTf.getText();
        JOptionPane.showMessageDialog(rootPane, "Geri iade edilen ücret :"+bakiye);
        bakiyeTf.setText("0");
    
        
    }//GEN-LAST:event_temizleBtActionPerformed

    private void bakiyeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyeTfActionPerformed
        

    }//GEN-LAST:event_bakiyeTfActionPerformed

    private void fantaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaRBActionPerformed

        if (fantaRB.isSelected()) {
            kolaRB.setSelected(false);
            gazozRB.setSelected(false);   
        }
    }//GEN-LAST:event_fantaRBActionPerformed

    private void gazozRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gazozRBActionPerformed
        if (gazozRB.isSelected()) {
            fantaRB.setSelected(false);
            kolaRB.setSelected(false);   
        }
    }//GEN-LAST:event_gazozRBActionPerformed
  
    private void tekrarEkleBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekrarEkleBtActionPerformed
        double bakiye;
        double para1;
        bakiye= Double.parseDouble((String) bakiyeTf.getText() );
        para1= Double.parseDouble((String) ekleCb.getSelectedItem());
        bakiyeTf.setText(Double.toString(para1+bakiye));       
    }//GEN-LAST:event_tekrarEkleBtActionPerformed

    private void ekleCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleCbActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ekleCbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otomat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otomat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otomat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otomat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otomat().setVisible(true);
            }
        });
    }
    //created by erdemmucahit

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alBt;
    private javax.swing.JTextField bakiyeTf;
    private javax.swing.JButton cikBt;
    private javax.swing.JComboBox<String> ekleCb;
    private javax.swing.JRadioButton fantaRB;
    private javax.swing.JRadioButton gazozRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton kolaRB;
    private javax.swing.JButton tekrarEkleBt;
    private javax.swing.JButton temizleBt;
    // End of variables declaration//GEN-END:variables
}
